import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cls } from '../lib/utils';
import { Modal } from './Modal';
const toAriaBoolean = (value) => (value ? 'true' : 'false');
export function SortDialog({ isOpen, onClose, sortBy, setSortBy, sortDirection, setSortDirection, shiny, setShiny, showMegas, setShowMegas, perPage, setPerPage, }) {
    const sortOpts = [
        { v: 'bayes', label: 'Coolness' },
        { v: 'name', label: 'Name' },
        { v: 'dex', label: 'Dex' },
        { v: 'gen', label: 'Gen' },
        { v: 'type', label: 'Type' },
    ];
    return (_jsx(Modal, { isOpen: isOpen, onClose: onClose, title: "Sort & Display", maxWidth: "max-w-lg", children: _jsxs("div", { className: "flex flex-col gap-5", children: [_jsxs("section", { children: [_jsx("div", { className: "filter-head", children: "Sort" }), _jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsx("div", { role: "tablist", "aria-label": "Sort", className: "segmented", children: sortOpts.map((o) => (_jsx("button", { type: "button", role: "tab", "aria-selected": toAriaBoolean(sortBy === o.v), className: cls('segmented-btn', sortBy === o.v && 'on'), onClick: () => setSortBy(o.v), children: o.label }, o.v))) }), sortBy !== 'bayes' && (_jsx("button", { type: "button", onClick: () => setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc'), className: "btn btn-secondary px-2 py-1 text-xs flex items-center gap-1", title: sortDirection === 'asc' ? 'Ascending' : 'Descending', children: sortDirection === 'asc' ? '↑' : '↓' }))] })] }), _jsxs("section", { className: "flex flex-wrap gap-6", children: [_jsxs("div", { children: [_jsx("div", { className: "filter-head", children: "Shiny" }), _jsxs("div", { role: "group", "aria-label": "Shiny variant", className: "segmented", children: [_jsx("button", { type: "button", className: cls('segmented-btn', !shiny && 'on'), "aria-pressed": toAriaBoolean(!shiny), onClick: () => setShiny(false), children: "Off" }), _jsx("button", { type: "button", className: cls('segmented-btn', shiny && 'on'), "aria-pressed": toAriaBoolean(shiny), onClick: () => setShiny(true), children: "\u2727 On" })] })] }), _jsxs("div", { children: [_jsx("div", { className: "filter-head", children: "Megas" }), _jsxs("div", { role: "group", "aria-label": "Show mega evolutions", className: "segmented", children: [_jsx("button", { type: "button", className: cls('segmented-btn', !showMegas && 'on'), "aria-pressed": toAriaBoolean(!showMegas), onClick: () => setShowMegas(false), children: "Hide" }), _jsx("button", { type: "button", className: cls('segmented-btn', showMegas && 'on'), "aria-pressed": toAriaBoolean(showMegas), onClick: () => setShowMegas(true), children: "Show" })] })] }), _jsxs("div", { children: [_jsx("div", { className: "filter-head", children: "Per Page" }), _jsx("div", { role: "group", "aria-label": "Items per page", className: "segmented", children: [10, 20, 50, 0].map(n => (_jsx("button", { type: "button", className: cls('segmented-btn', perPage === n && 'on'), "aria-pressed": toAriaBoolean(perPage === n), onClick: () => setPerPage(n), children: n === 0 ? 'All' : n }, n))) })] })] }), _jsx("div", { className: "flex justify-end", children: _jsx("button", { type: "button", className: "btn btn-accent px-4 py-2 text-sm", onClick: onClose, children: "Done" }) })] }) }));
}
